//! 編譯期把 themes/*.toml 轉成 Rust 靜態 `THEMES` 表，嵌入到 crate。
//! toml/serde 只在此（build-dependency）出現，不進最終 wasm 依賴圖。
//! {{palette}} 變數在此解析；{{accent}} 保留給執行期替換（供自訂強調色）。

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::{env, fs};
use toml::Value;

fn main() {
    println!("cargo:rerun-if-changed=themes");
    let dir = Path::new("themes");
    let mut paths: Vec<PathBuf> = fs::read_dir(dir)
        .expect("themes/ directory must exist")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "toml"))
        .collect();
    paths.sort();
    assert!(!paths.is_empty(), "at least one theme .toml is required");

    let mut out = String::new();
    out.push_str("// @generated by build.rs from themes/*.toml — do not edit\n");
    out.push_str("pub static THEMES: &[Theme] = &[\n");
    for p in &paths {
        println!("cargo:rerun-if-changed={}", p.display());
        let text = fs::read_to_string(p).unwrap();
        let v: Value = text
            .parse()
            .unwrap_or_else(|e| panic!("parse {}: {e}", p.display()));
        out.push_str(&emit_theme(&v, p));
    }
    out.push_str("];\n");

    let od = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&od).join("themes_gen.rs"), out).unwrap();

    // 僅在 syntax-highlight feature 開啟時產出精簡語法/主題 dump。
    if env::var_os("CARGO_FEATURE_SYNTAX_HIGHLIGHT").is_some() {
        generate_syntax_dumps(&od);
    }
}

/// 產出高亮所需的語法/主題 dump（僅在 syntax-highlight feature 開啟時呼叫）。
/// 未壓縮是刻意的：HTTP 層 gzip/brotli 會壓，執行期便不必把 flate2 帶進 wasm。
///
/// 注意：syntect 的完整語法集含跨語言 embed（HTML 內嵌 CSS/JS…），以 index 互相
/// 參照，無法安全地「抽子集再 build」（會 panic）。要真正縮小語法包，必須從
/// 各語言的 .sublime-syntax 原始檔重新解析建置——列為後續最佳化任務。此處先 dump
/// 完整語法集（feature 開啟本就接受大體積），主題則可安全取子集。
fn generate_syntax_dumps(out_dir: &str) {
    use syntect::dumps::dump_to_uncompressed_file;
    use syntect::highlighting::ThemeSet;
    use syntect::parsing::SyntaxSet;

    const THEMES: &[&str] = &["InspiredGitHub", "base16-ocean.dark"];

    let syntaxes = SyntaxSet::load_defaults_newlines();
    dump_to_uncompressed_file(&syntaxes, Path::new(out_dir).join("syntaxes.packdump"))
        .expect("dump syntaxes");

    let all = ThemeSet::load_defaults();
    let mut ts = ThemeSet::new();
    for name in THEMES {
        if let Some(t) = all.themes.get(*name) {
            ts.themes.insert((*name).to_string(), t.clone());
        }
    }
    dump_to_uncompressed_file(&ts, Path::new(out_dir).join("themes.packdump"))
        .expect("dump themes");
}

fn emit_theme(v: &Value, path: &Path) -> String {
    let meta = v
        .get("meta")
        .and_then(Value::as_table)
        .unwrap_or_else(|| panic!("{}: missing [meta]", path.display()));
    let get = |k: &str| {
        meta.get(k)
            .and_then(Value::as_str)
            .unwrap_or_else(|| panic!("{}: meta.{k} missing", path.display()))
    };
    let (id, name, desc, accent) = (get("id"), get("name"), get("description"), get("accent"));

    let mut vars: BTreeMap<String, String> = BTreeMap::new();
    if let Some(pal) = v.get("palette").and_then(Value::as_table) {
        for (k, val) in pal {
            vars.insert(k.clone(), val.as_str().unwrap_or_default().to_string());
        }
    }
    resolve_map(&mut vars);

    let root = emit_style(v.get("root").and_then(Value::as_table), &vars);

    let mut elems = String::from("&[");
    if let Some(els) = v.get("elements").and_then(Value::as_table) {
        let mut keys: Vec<&String> = els.keys().collect();
        keys.sort();
        for k in keys {
            let st = emit_style(els.get(k).and_then(Value::as_table), &vars);
            elems.push_str(&format!("({k:?}, {st}),"));
        }
    }
    elems.push(']');

    let code = v.get("code").and_then(Value::as_table);
    let code_theme = code
        .and_then(|c| c.get("theme"))
        .and_then(Value::as_str)
        .unwrap_or("InspiredGitHub");
    let code_block = emit_style(
        code.and_then(|c| c.get("block")).and_then(Value::as_table),
        &vars,
    );

    format!(
        "Theme {{ meta: ThemeMeta {{ id: {id:?}, name: {name:?}, description: {desc:?}, accent: {accent:?} }}, \
         root: {root}, elements: {elems}, \
         code: CodeStyle {{ theme: {code_theme:?}, block: {code_block} }} }},\n"
    )
}

fn emit_style(
    t: Option<&toml::map::Map<String, Value>>,
    vars: &BTreeMap<String, String>,
) -> String {
    let mut s = String::from("&[");
    if let Some(t) = t {
        let mut keys: Vec<&String> = t.keys().collect();
        keys.sort();
        for k in keys {
            if let Some(val) = t.get(k).and_then(Value::as_str) {
                let resolved = resolve_str(val, vars);
                s.push_str(&format!("({k:?}, {resolved:?}),"));
            }
        }
    }
    s.push(']');
    s
}

/// 反覆把 {{key}} 替換為 palette 值，直到穩定；{{accent}} 不在 vars，故保留。
fn resolve_str(s: &str, vars: &BTreeMap<String, String>) -> String {
    let mut cur = s.to_string();
    for _ in 0..12 {
        let mut changed = false;
        for (k, val) in vars {
            let pat = format!("{{{{{k}}}}}");
            if cur.contains(&pat) {
                cur = cur.replace(&pat, val);
                changed = true;
            }
        }
        if !changed {
            break;
        }
    }
    cur
}

/// 解析 palette 內部互相引用（例如 quote-bar = "{{accent}}"）。
fn resolve_map(vars: &mut BTreeMap<String, String>) {
    for _ in 0..12 {
        let snapshot = vars.clone();
        let mut changed = false;
        for v in vars.values_mut() {
            for (rk, rv) in &snapshot {
                let pat = format!("{{{{{rk}}}}}");
                if v.contains(&pat) {
                    *v = v.replace(&pat, rv);
                    changed = true;
                }
            }
        }
        if !changed {
            break;
        }
    }
}
